name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths: "./**"
  workflow_dispatch:   

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - 
      name: Checkout
      uses: actions/checkout@v2.4.2
    - 
      uses: docker/login-action@v2
      name: Login to Docker Hub
      with:
        username: ${{ secrets.SECRET_DH_UN }}
        password: ${{ secrets.SECRET_DH_REPO_SPECIFIC_TOKEN }}
    - 
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.SECRET_DH_UN }}/socketiot:${{ github.sha }}
