name: build-push-opc-ua-broker-dockerimage

on:
  push:
    branches:
      - master
    
  workflow_dispatch:

jobs:
  buildandpush:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.RG_NAME }}commonacr/industrystack.opcuabroker:${{ github.sha }}
